apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: flight-reservation
type: Opaque
stringData:
  username: admin
  password: Jenkinspractice
  dbname: flightdb
  host: terraform-20260428104128005400000001.c7i6oe8w0yg8.ap-south-1.rds.amazonaws.com

