apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-app
  template:
    metadata:
      labels:
        app: flight-app
    spec:
      containers:
      - name: flight-app
        image: 56805/flight-app:latest
        ports:
        - containerPort: 8080